/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c2d9a15e728e
 */

import { getInsightsPolymarketUpDown15min } from "../../funcs/getInsightsPolymarketUpDown15min.js";
import { GetInsightsPolymarketUpDown15minRequest$zodSchema } from "../../models/getinsightspolymarketupdown15minop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsPolymarketUpDown15minRequest$zodSchema.optional(),
};

export const tool$getInsightsPolymarketUpDown15min: ToolDefinition<
  typeof args
> = {
  name: "get-insights-polymarket-up-down-15min",
  description: `Insight - Polymarket up/down 15 minutes

Get SynthData's estimated fair probabilities alongside live Polymarket odds for 15 minutes Up/Down contracts. Returns both synth and Polymarket probabilities, current outcome, and order book data (best bid/ask). Compare to identify mispriced bets on shorter timeframes. Supported assets: BTC, ETH, SOL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsPolymarketUpDown15min(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
