/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getInsightsLpBounds } from "../../funcs/getInsightsLpBounds.js";
import { GetInsightsLpBoundsRequest$zodSchema } from "../../models/getinsightslpboundsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsLpBoundsRequest$zodSchema.optional(),
};

export const tool$getInsightsLpBounds: ToolDefinition<typeof args> = {
  name: "get-insights-lp-bounds",
  description: `Insight - Liquidity provider bounds

It selects the top 'limit' miners from the the meta-leaderboard to calculate price intervals and probability to stay in each interval for the next 24 hours, expected time to stay in each interval and impermanent loss.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsLpBounds(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
