/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2176ca44759b
 */

import { getInsightsLimitless15min } from "../../funcs/getInsightsLimitless15min.js";
import { GetInsightsLimitless15minRequest$zodSchema } from "../../models/getinsightslimitless15minop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsLimitless15minRequest$zodSchema.optional(),
};

export const tool$getInsightsLimitless15min: ToolDefinition<typeof args> = {
  name: "get-insights-limitless-15min",
  description: `Insight - Limitless 15 minutes

Get SynthData's estimated fair probabilities alongside live Limitless odds for 15 minutes contracts. Returns both synth and Limitless probabilities, current outcome, and order book data (best bid/ask). Compare to identify mispriced bets on shorter timeframes. Supported assets: BTC, ETH, SOL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsLimitless15min(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
