/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 68d48f874d49
 */

import { getInsightsPolymarketUpDownDaily } from "../../funcs/getInsightsPolymarketUpDownDaily.js";
import { GetInsightsPolymarketUpDownDailyRequest$zodSchema } from "../../models/getinsightspolymarketupdowndailyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsPolymarketUpDownDailyRequest$zodSchema.optional(),
};

export const tool$getInsightsPolymarketUpDownDaily: ToolDefinition<
  typeof args
> = {
  name: "get-insights-polymarket-up-down-daily",
  description: `Insight - Polymarket up/down daily

It selects the top 'limit' miners from the the meta-leaderboard to compare polymarket and synth probability and outcome.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsPolymarketUpDownDaily(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
