/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dfed045b7d32
 */

import { getInsightsLpBounds } from "../../funcs/getInsightsLpBounds.js";
import { GetInsightsLpBoundsRequest$zodSchema } from "../../models/getinsightslpboundsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsLpBoundsRequest$zodSchema.optional(),
};

export const tool$getInsightsLpBounds: ToolDefinition<typeof args> = {
  name: "get-insights-lp-bounds",
  description: `Insight - Liquidity provider bounds

Get price interval analysis for an asset over the next 24 hours. Returns price intervals with the probability of price staying within each interval, expected time in-range, and estimated impermanent loss. Useful for concentrated liquidity positioning, options strike selection, and range-bound trading strategies. Supported assets: BTC, ETH, XAU, SOL, SPY, NVDA, GOOGL, TSLA, AAPL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsLpBounds(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
