/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 236e430e069f
 */

import { getInsightsVolatility } from "../../funcs/getInsightsVolatility.js";
import { GetInsightsVolatilityRequest$zodSchema } from "../../models/getinsightsvolatilityop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsVolatilityRequest$zodSchema.optional(),
};

export const tool$getInsightsVolatility: ToolDefinition<typeof args> = {
  name: "get-insights-volatility",
  description: `Insight - Volatility

It selects the top 'limit' miners from the the meta-leaderboard to calculate the volatility.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsVolatility(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
