/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f9c78bf6a832
 */

import { getInsightsPolymarketUpDownHourly } from "../../funcs/getInsightsPolymarketUpDownHourly.js";
import { GetInsightsPolymarketUpDownHourlyRequest$zodSchema } from "../../models/getinsightspolymarketupdownhourlyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsPolymarketUpDownHourlyRequest$zodSchema.optional(),
};

export const tool$getInsightsPolymarketUpDownHourly: ToolDefinition<
  typeof args
> = {
  name: "get-insights-polymarket-up-down-hourly",
  description: `Insight - Polymarket up/down hourly

Get SynthData's estimated fair probabilities alongside live Polymarket odds for hourly Up/Down contracts. Returns both synth and Polymarket probabilities, current outcome, and order book data (best bid/ask). Compare to identify mispriced bets on shorter timeframes. Supported assets: BTC, ETH, XAU, SOL, SPY, NVDA, GOOGL, TSLA, AAPL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsPolymarketUpDownHourly(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
