/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 36dd8388723b
 */

import { getInsightsLpProbabilities } from "../../funcs/getInsightsLpProbabilities.js";
import { GetInsightsLpProbabilitiesRequest$zodSchema } from "../../models/getinsightslpprobabilitiesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsLpProbabilitiesRequest$zodSchema.optional(),
};

export const tool$getInsightsLpProbabilities: ToolDefinition<typeof args> = {
  name: "get-insights-lp-probabilities",
  description: `Insight - Liquidity provider probabilities

Get the probability of an asset's price being above or below specific price targets over the next 24 hours. Returns probabilities for 11 upside and 11 downside price levels relative to the current price. Useful for options strike selection, Polymarket up/down contracts, and directional risk assessment. Supported assets: BTC, ETH, XAU, SOL, SPY, NVDA, GOOGL, TSLA, AAPL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsLpProbabilities(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
