/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 36dd8388723b
 */

import { getInsightsLpProbabilities } from "../../funcs/getInsightsLpProbabilities.js";
import { GetInsightsLpProbabilitiesRequest$zodSchema } from "../../models/getinsightslpprobabilitiesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsLpProbabilitiesRequest$zodSchema.optional(),
};

export const tool$getInsightsLpProbabilities: ToolDefinition<typeof args> = {
  name: "get-insights-lp-probabilities",
  description: `Insight - Liquidity provider probabilities

Get long and short liquidation probability estimates for an asset at various price levels. Returns the probability of liquidation within 6, 12, 18, and 24 hour windows for both long and short positions. Useful for assessing leverage risk, setting stop-loss levels, and managing margin exposure.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsLpProbabilities(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
