/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 120bef4dc6f6
 */

import { getInsightsLimitlessHourly } from "../../funcs/getInsightsLimitlessHourly.js";
import { GetInsightsLimitlessHourlyRequest$zodSchema } from "../../models/getinsightslimitlesshourlyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsLimitlessHourlyRequest$zodSchema.optional(),
};

export const tool$getInsightsLimitlessHourly: ToolDefinition<typeof args> = {
  name: "get-insights-limitless-hourly",
  description: `Insight - Limitless hourly

Get SynthData's estimated fair probabilities alongside live Limitless odds for hourly contracts. Returns both synth and Limitless probabilities, current outcome, and order book data (best bid/ask). Compare to identify mispriced bets on shorter timeframes. Supported assets: BTC, ETH, SOL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsLimitlessHourly(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
