/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getInsightsLiquidation } from "../../funcs/getInsightsLiquidation.js";
import { GetInsightsLiquidationRequest$zodSchema } from "../../models/getinsightsliquidationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsLiquidationRequest$zodSchema.optional(),
};

export const tool$getInsightsLiquidation: ToolDefinition<typeof args> = {
  name: "get-insights-liquidation",
  description: `Insight - Liquidation probability

It selects the top 'limit' miners from the the meta-leaderboard to calculate the probability of liquidation in 6, 12, 18 and 24 hours for different price levels.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsLiquidation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
