/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ffe682f0f808
 */

import { getInsightsLimitlessDaily } from "../../funcs/getInsightsLimitlessDaily.js";
import { GetInsightsLimitlessDailyRequest$zodSchema } from "../../models/getinsightslimitlessdailyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsLimitlessDailyRequest$zodSchema.optional(),
};

export const tool$getInsightsLimitlessDaily: ToolDefinition<typeof args> = {
  name: "get-insights-limitless-daily",
  description: `Insight - Limitless daily

Get SynthData's estimated fair probabilities alongside live Limitless odds for daily contracts. Returns both synth and Limitless probabilities, current outcome, and order book data (best bid/ask). Compare to identify mispriced bets. Supported assets: BTC, ETH, SOL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsLimitlessDaily(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
