/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 836207daae21
 */

import { getInsightsLiquidation } from "../../funcs/getInsightsLiquidation.js";
import { GetInsightsLiquidationRequest$zodSchema } from "../../models/getinsightsliquidationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsLiquidationRequest$zodSchema.optional(),
};

export const tool$getInsightsLiquidation: ToolDefinition<typeof args> = {
  name: "get-insights-liquidation",
  description: `Insight - Liquidation probability

Get long and short liquidation probability estimates for an asset at various price levels. Returns the probability of liquidation within 6, 12, 18, and 24 hour windows for both long and short positions. Useful for assessing leverage risk, setting stop-loss levels, and managing margin exposure. Supported assets: BTC, ETH, XAU, SOL, SPY, NVDA, GOOGL, TSLA, AAPL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsLiquidation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
