/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 54db83170089
 */

import { getInsightsPolymarketUpDown5min } from "../../funcs/getInsightsPolymarketUpDown5min.js";
import { GetInsightsPolymarketUpDown5minRequest$zodSchema } from "../../models/getinsightspolymarketupdown5minop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsPolymarketUpDown5minRequest$zodSchema.optional(),
};

export const tool$getInsightsPolymarketUpDown5min: ToolDefinition<typeof args> =
  {
    name: "get-insights-polymarket-up-down-5min",
    description: `Insight - Polymarket up/down 5 minutes

Get SynthData's estimated fair probabilities alongside live Polymarket odds for 5 minutes Up/Down contracts. Returns both synth and Polymarket probabilities, current outcome, and order book data (best bid/ask). Compare to identify mispriced bets on shorter timeframes. Supported assets: BTC, ETH, SOL.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await getInsightsPolymarketUpDown5min(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
