/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1eb8cd660eb1
 */

import { getInsightsPolymarketRange } from "../../funcs/getInsightsPolymarketRange.js";
import { GetInsightsPolymarketRangeRequest$zodSchema } from "../../models/getinsightspolymarketrangeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsPolymarketRangeRequest$zodSchema.optional(),
};

export const tool$getInsightsPolymarketRange: ToolDefinition<typeof args> = {
  name: "get-insights-polymarket-range",
  description: `Insight - Polymarket price range

Get SynthData's estimated fair probabilities alongside live Polymarket odds for daily price range contracts. Returns both synth and Polymarket probabilities per range, current outcome, and order book data. Compare to identify mispriced range bets. Supported assets: BTC, ETH, SOL, NVDA, GOOGL, TSLA, AAPL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsPolymarketRange(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
