/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getInsightsLpProbabilities } from "../../funcs/getInsightsLpProbabilities.js";
import { GetInsightsLpProbabilitiesRequest$zodSchema } from "../../models/getinsightslpprobabilitiesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsLpProbabilitiesRequest$zodSchema.optional(),
};

export const tool$getInsightsLpProbabilities: ToolDefinition<typeof args> = {
  name: "get-insights-lp-probabilities",
  description: `Insight - Liquidity provider probabilities

Calculate the probability of asset price to be above 11 prices and bellow 11 prices.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsLpProbabilities(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
