/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 87a055b0d027
 */

import { getInsightsOptionPricing } from "../../funcs/getInsightsOptionPricing.js";
import { GetInsightsOptionPricingRequest$zodSchema } from "../../models/getinsightsoptionpricingop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInsightsOptionPricingRequest$zodSchema.optional(),
};

export const tool$getInsightsOptionPricing: ToolDefinition<typeof args> = {
  name: "get-insights-option-pricing",
  description: `Insight - Option pricing

Get SynthData-derived option prices for an asset. Returns theoretical call and put prices across a range of strike prices with expiry time, using SynthData's ensemble volatility forecasts. Compare against market-quoted premiums to identify mispriced options. Supported assets: BTC, ETH, SOL, SPY, NVDA, GOOGL, TSLA, AAPL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getInsightsOptionPricing(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
