/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bf93d6f7db51
 */

import { getPredictionPercentiles } from "../../funcs/getPredictionPercentiles.js";
import { GetPredictionPercentilesRequest$zodSchema } from "../../models/getpredictionpercentilesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPredictionPercentilesRequest$zodSchema.optional(),
};

export const tool$getPredictionPercentiles: ToolDefinition<typeof args> = {
  name: "get-prediction-percentiles",
  description: `Prediction Percentiles - meta model from top 10 miners

Get price distribution percentiles for an asset over the 24-hour forecast horizon. Returns predicted prices at 9 percentile levels (0.5th, 5th, 20th, 35th, 50th, 65th, 80th, 95th, 99.5th), giving the full probability distribution of expected price movements. Useful for position sizing, setting price targets, and understanding tail risk. Supported assets: BTC, ETH, XAU, SOL, SPY, NVDA, GOOGL, TSLA, AAPL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getPredictionPercentiles(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
