/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getPredictionPercentiles } from "../../funcs/getPredictionPercentiles.js";
import { GetPredictionPercentilesRequest$zodSchema } from "../../models/getpredictionpercentilesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPredictionPercentilesRequest$zodSchema.optional(),
};

export const tool$getPredictionPercentiles: ToolDefinition<typeof args> = {
  name: "get-prediction-percentiles",
  description: `Prediction Percentiles - meta model from top 10 miners

Get price distribution percentiles over the forecast horizon.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getPredictionPercentiles(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
