/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9bdc68fbee96
 */

import { getV2PredictionBest } from "../../funcs/getV2PredictionBest.js";
import { GetV2PredictionBestRequest$zodSchema } from "../../models/getv2predictionbestop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV2PredictionBestRequest$zodSchema,
};

export const tool$getV2PredictionBest: ToolDefinition<typeof args> = {
  name: "get-v2-prediction-best",
  description: `Predictions - Best Prediction Rates

Gets the latest prediction rates of the current best miner.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getV2PredictionBest(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
