/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getValidationMiner } from "../../funcs/getValidationMiner.js";
import { GetValidationMinerRequest$zodSchema } from "../../models/getvalidationminerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetValidationMinerRequest$zodSchema,
};

export const tool$getValidationMiner: ToolDefinition<typeof args> = {
  name: "get-validation-miner",
  description: `Validations - Miner Validation

Gets the validation status for a specific miner`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getValidationMiner(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
