/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getV2LeaderboardLatest } from "../../funcs/getV2LeaderboardLatest.js";
import { GetV2LeaderboardLatestRequest$zodSchema } from "../../models/getv2leaderboardlatestop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV2LeaderboardLatestRequest$zodSchema.optional(),
};

export const tool$getV2LeaderboardLatest: ToolDefinition<typeof args> = {
  name: "get-v2-leaderboard-latest",
  description: `Leaderboard - Latest Leaderboard V2

Gets the current leaderboard.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getV2LeaderboardLatest(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
