/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getValidationScoresLatest } from "../../funcs/getValidationScoresLatest.js";
import { GetValidationScoresLatestRequest$zodSchema } from "../../models/getvalidationscoreslatestop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetValidationScoresLatestRequest$zodSchema.optional(),
};

export const tool$getValidationScoresLatest: ToolDefinition<typeof args> = {
  name: "get-validation-scores-latest",
  description: `Validations - Latest Scores

Gets the most recent validation scores for all miners`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getValidationScoresLatest(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
