/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getV2MetaLeaderboardHistorical } from "../../funcs/getV2MetaLeaderboardHistorical.js";
import { GetV2MetaLeaderboardHistoricalRequest$zodSchema } from "../../models/getv2metaleaderboardhistoricalop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV2MetaLeaderboardHistoricalRequest$zodSchema,
};

export const tool$getV2MetaLeaderboardHistorical: ToolDefinition<typeof args> =
  {
    name: "get-v2-meta-leaderboard-historical",
    description: `Leaderboard - Meta-Leaderboard History V2

Gets the meta-leaderboard history, which aggregates miners' incentives over a period of days in the past.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await getV2MetaLeaderboardHistorical(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
