/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ddac7ece5130
 */

import { getV2LeaderboardHistorical } from "../../funcs/getV2LeaderboardHistorical.js";
import { GetV2LeaderboardHistoricalRequest$zodSchema } from "../../models/getv2leaderboardhistoricalop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV2LeaderboardHistoricalRequest$zodSchema,
};

export const tool$getV2LeaderboardHistorical: ToolDefinition<typeof args> = {
  name: "get-v2-leaderboard-historical",
  description: `Leaderboard -  Leaderboard History V2

Gets the leaderboard history.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getV2LeaderboardHistorical(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
