/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getV2MetaLeaderboardLatest } from "../../funcs/getV2MetaLeaderboardLatest.js";
import { GetV2MetaLeaderboardLatestRequest$zodSchema } from "../../models/getv2metaleaderboardlatestop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV2MetaLeaderboardLatestRequest$zodSchema.optional(),
};

export const tool$getV2MetaLeaderboardLatest: ToolDefinition<typeof args> = {
  name: "get-v2-meta-leaderboard-latest",
  description: `Leaderboard - Latest Meta-Leaderboard V2

Get the current meta-leaderboard, which aggregates miners' incentives over a period of days. This provides another way to rank prediction accuracy, thereby increasing stability.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getV2MetaLeaderboardLatest(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
