/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getV2PredictionHistorical } from "../../funcs/getV2PredictionHistorical.js";
import { GetV2PredictionHistoricalRequest$zodSchema } from "../../models/getv2predictionhistoricalop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV2PredictionHistoricalRequest$zodSchema,
};

export const tool$getV2PredictionHistorical: ToolDefinition<typeof args> = {
  name: "get-v2-prediction-historical",
  description: `Predictions - Historical Prediction Rates

Gets the historical prediction rates.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getV2PredictionHistorical(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
