/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getV2PredictionLatest } from "../../funcs/getV2PredictionLatest.js";
import { GetV2PredictionLatestRequest$zodSchema } from "../../models/getv2predictionlatestop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV2PredictionLatestRequest$zodSchema,
};

export const tool$getV2PredictionLatest: ToolDefinition<typeof args> = {
  name: "get-v2-prediction-latest",
  description: `Predictions - Latest Prediction Rates

Gets the latest valid prediction rates.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getV2PredictionLatest(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
