/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c7160ec1333c
 */

import { getValidationScoresHistorical } from "../../funcs/getValidationScoresHistorical.js";
import { GetValidationScoresHistoricalRequest$zodSchema } from "../../models/getvalidationscoreshistoricalop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetValidationScoresHistoricalRequest$zodSchema,
};

export const tool$getValidationScoresHistorical: ToolDefinition<typeof args> = {
  name: "get-validation-scores-historical",
  description: `Validations - Historical Scores

Gets the validation scores for all miners between two dates`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await getValidationScoresHistorical(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
