/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2784dd48e82a
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { SynthCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool, registerDynamicTools } from "./tools.js";
import { tool$getInsightsLiquidation } from "./tools/getInsightsLiquidation.js";
import { tool$getInsightsLpBounds } from "./tools/getInsightsLpBounds.js";
import { tool$getInsightsLpProbabilities } from "./tools/getInsightsLpProbabilities.js";
import { tool$getInsightsOptionPricing } from "./tools/getInsightsOptionPricing.js";
import { tool$getInsightsPolymarketRange } from "./tools/getInsightsPolymarketRange.js";
import { tool$getInsightsPolymarketUpDownDaily } from "./tools/getInsightsPolymarketUpDownDaily.js";
import { tool$getInsightsPolymarketUpDownHourly } from "./tools/getInsightsPolymarketUpDownHourly.js";
import { tool$getInsightsVolatility } from "./tools/getInsightsVolatility.js";
import { tool$getPredictionPercentiles } from "./tools/getPredictionPercentiles.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => SynthCore;
  serverURL: string;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Synth",
    version: "0.0.12",
  });

  const getClient = deps.getSDK || (() =>
    new SynthCore({
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$getInsightsLiquidation);
  tool(tool$getInsightsLpBounds);
  tool(tool$getInsightsLpProbabilities);
  tool(tool$getInsightsOptionPricing);
  tool(tool$getInsightsPolymarketRange);
  tool(tool$getInsightsPolymarketUpDownDaily);
  tool(tool$getInsightsPolymarketUpDownHourly);
  tool(tool$getInsightsVolatility);
  tool(tool$getPredictionPercentiles);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
