workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Synth API:
        inputs:
            - location: .speakeasy/in.openapi.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/synth-data/synthdata/synth-mcp
targets:
    synth:
        target: mcp-typescript
        source: Synth API
