/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d34ee6640bd2
 */

import * as z from "zod";
import {
  TypesOptionPricingResponse,
  TypesOptionPricingResponse$zodSchema,
} from "./typesoptionpricingresponse.js";

export type GetInsightsOptionPricingRequest = {
  asset?: string | undefined;
  prompt_name?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsOptionPricingRequest$zodSchema: z.ZodType<
  GetInsightsOptionPricingRequest
> = z.object({
  asset: z.string().describe(
    "Symbol of the asset: BTC, ETH, SOL, JITOSOL, SPY, NVDA, GOOGL, TSLA, AAPL",
  ).optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
  prompt_name: z.string().describe(
    "Forecast horizon: 1h for next-hour or 24h for next-day price intervals (default: 24h)",
  ).optional(),
});

export type GetInsightsOptionPricingResponse =
  | TypesOptionPricingResponse
  | string
  | string;

export const GetInsightsOptionPricingResponse$zodSchema: z.ZodType<
  GetInsightsOptionPricingResponse
> = z.union([
  TypesOptionPricingResponse$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
