/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: de46aeb04e42
 */

import * as z from "zod";
import {
  TypesLiquidationProbabilityResponse,
  TypesLiquidationProbabilityResponse$zodSchema,
} from "./typesliquidationprobabilityresponse.js";

export type GetInsightsLiquidationRequest = {
  asset?: string | undefined;
  horizon?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsLiquidationRequest$zodSchema: z.ZodType<
  GetInsightsLiquidationRequest
> = z.object({
  asset: z.string().describe(
    "Symbol of the asset: BTC, ETH, XAU, SOL, JITOSOL, SPY, NVDA, GOOGL, TSLA, AAPL",
  ).optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  horizon: z.string().describe(
    "Forecast horizon: 1h for next-hour or 24h for next-day price intervals (default: 24h)",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
});

export type GetInsightsLiquidationResponse =
  | TypesLiquidationProbabilityResponse
  | string
  | string;

export const GetInsightsLiquidationResponse$zodSchema: z.ZodType<
  GetInsightsLiquidationResponse
> = z.union([
  TypesLiquidationProbabilityResponse$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
