/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c1c031026011
 */

import * as z from "zod";
import {
  TypesLimitlessMarket,
  TypesLimitlessMarket$zodSchema,
} from "./typeslimitlessmarket.js";

export type GetInsightsLimitlessHourlyRequest = {
  asset?: string | undefined;
  horizon?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsLimitlessHourlyRequest$zodSchema: z.ZodType<
  GetInsightsLimitlessHourlyRequest
> = z.object({
  asset: z.string().describe("Symbol of the asset: BTC, ETH, SOL").optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14 if horizon=24h, 6 if horizon=1h). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  horizon: z.string().describe(
    "Forecast horizon: 1h for next-hour or 24h for next-day price intervals (default: 1h)",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
});

export type GetInsightsLimitlessHourlyResponse =
  | Array<TypesLimitlessMarket>
  | string
  | string;

export const GetInsightsLimitlessHourlyResponse$zodSchema: z.ZodType<
  GetInsightsLimitlessHourlyResponse
> = z.union([
  z.array(TypesLimitlessMarket$zodSchema).describe("OK"),
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
