/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: deaa17e70a78
 */

import * as z from "zod";
import {
  TypesLPBoundsResponse,
  TypesLPBoundsResponse$zodSchema,
} from "./typeslpboundsresponse.js";

export type GetInsightsLpBoundsRequest = {
  asset?: string | undefined;
  prompt_name?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsLpBoundsRequest$zodSchema: z.ZodType<
  GetInsightsLpBoundsRequest
> = z.object({
  asset: z.string().describe(
    "Symbol of the asset: BTC, ETH, XAU, SOL, JITOSOL, SPY, NVDA, GOOGL, TSLA, AAPL",
  ).optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
  prompt_name: z.string().describe(
    "Forecast horizon: 1h for next-hour or 24h for next-day price intervals (default: 24h)",
  ).optional(),
});

export type GetInsightsLpBoundsResponse =
  | TypesLPBoundsResponse
  | string
  | string;

export const GetInsightsLpBoundsResponse$zodSchema: z.ZodType<
  GetInsightsLpBoundsResponse
> = z.union([
  TypesLPBoundsResponse$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
