/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fc81f0e8562c
 */

import * as z from "zod";
import {
  TypesPolymarketUpDownResponse,
  TypesPolymarketUpDownResponse$zodSchema,
} from "./typespolymarketupdownresponse.js";

export type GetInsightsPolymarketUpDownHourlyRequest = {
  asset?: string | undefined;
  horizon?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsPolymarketUpDownHourlyRequest$zodSchema: z.ZodType<
  GetInsightsPolymarketUpDownHourlyRequest
> = z.object({
  asset: z.string().describe("Symbol of the asset: BTC, ETH, SOL").optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  horizon: z.string().describe(
    "Forecast horizon: 1h for next-hour or 24h for next-day price intervals (default: 24h)",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
});

export type GetInsightsPolymarketUpDownHourlyResponse =
  | TypesPolymarketUpDownResponse
  | string
  | string;

export const GetInsightsPolymarketUpDownHourlyResponse$zodSchema: z.ZodType<
  GetInsightsPolymarketUpDownHourlyResponse
> = z.union([
  TypesPolymarketUpDownResponse$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
