/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 940742f12963
 */

import * as z from "zod";
import {
  TypesPredictionPercentiles,
  TypesPredictionPercentiles$zodSchema,
} from "./typespredictionpercentiles.js";

export type GetInsightsPredictionPercentilesRequest = {
  asset?: string | undefined;
  horizon?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsPredictionPercentilesRequest$zodSchema: z.ZodType<
  GetInsightsPredictionPercentilesRequest
> = z.object({
  asset: z.string().describe(
    "Symbol of the asset: BTC, ETH, XAU, SOL, JITOSOL, SPY, NVDA, GOOGL, TSLA, AAPL",
  ).optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  horizon: z.string().describe(
    "Forecast horizon: 1h for next-hour or 24h for next-day price intervals (default: 24h)",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
});

export type GetInsightsPredictionPercentilesResponse =
  | TypesPredictionPercentiles
  | string
  | string;

export const GetInsightsPredictionPercentilesResponse$zodSchema: z.ZodType<
  GetInsightsPredictionPercentilesResponse
> = z.union([
  TypesPredictionPercentiles$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
