/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1e271dd44cbd
 */

import * as z from "zod";
import {
  TypesPriceRangeMarket,
  TypesPriceRangeMarket$zodSchema,
} from "./typespricerangemarket.js";

export type GetInsightsPolymarketRangeRequest = {
  asset?: string | undefined;
  horizon?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsPolymarketRangeRequest$zodSchema: z.ZodType<
  GetInsightsPolymarketRangeRequest
> = z.object({
  asset: z.string().describe(
    "Symbol of the asset: BTC, ETH, SOL, NVDA, GOOGL, TSLA, AAPL",
  ).optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  horizon: z.string().describe(
    "Forecast horizon: 1h for next-hour or 24h for next-day price intervals (default: 24h)",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
});

export type GetInsightsPolymarketRangeResponse =
  | Array<TypesPriceRangeMarket>
  | string
  | string;

export const GetInsightsPolymarketRangeResponse$zodSchema: z.ZodType<
  GetInsightsPolymarketRangeResponse
> = z.union([
  z.array(TypesPriceRangeMarket$zodSchema).describe("OK"),
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
