/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesOptionPricingResponse,
  TypesOptionPricingResponse$zodSchema,
} from "./typesoptionpricingresponse.js";

export type GetInsightsOptionPricingRequest = {
  asset?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsOptionPricingRequest$zodSchema: z.ZodType<
  GetInsightsOptionPricingRequest
> = z.object({
  asset: z.string().describe(
    "the symbol of the asset: BTC, ETH, XAU, SOL, SPYX, NVDAX, TSLAX, AAPLX, GOOGLX",
  ).optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
});

export type GetInsightsOptionPricingResponse =
  | TypesOptionPricingResponse
  | string
  | string;

export const GetInsightsOptionPricingResponse$zodSchema: z.ZodType<
  GetInsightsOptionPricingResponse
> = z.union([
  TypesOptionPricingResponse$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
