/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesPolymarketUpDownResponse,
  TypesPolymarketUpDownResponse$zodSchema,
} from "./typespolymarketupdownresponse.js";

export type GetInsightsPolymarketUpDownHourlyRequest = {
  asset?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsPolymarketUpDownHourlyRequest$zodSchema: z.ZodType<
  GetInsightsPolymarketUpDownHourlyRequest
> = z.object({
  asset: z.string().describe(
    "the symbol of the asset: BTC, ETH, XAU, SOL, SPYX, NVDAX, TSLAX, AAPLX, GOOGLX",
  ).optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
});

export type GetInsightsPolymarketUpDownHourlyResponse =
  | TypesPolymarketUpDownResponse
  | string
  | string;

export const GetInsightsPolymarketUpDownHourlyResponse$zodSchema: z.ZodType<
  GetInsightsPolymarketUpDownHourlyResponse
> = z.union([
  TypesPolymarketUpDownResponse$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
