/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1e3500bc08a4
 */

import * as z from "zod";
import {
  TypesLPProbabilitiesResponse,
  TypesLPProbabilitiesResponse$zodSchema,
} from "./typeslpprobabilitiesresponse.js";

export type GetInsightsLpProbabilitiesRequest = {
  asset?: string | undefined;
  prompt_name?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsLpProbabilitiesRequest$zodSchema: z.ZodType<
  GetInsightsLpProbabilitiesRequest
> = z.object({
  asset: z.string().describe(
    "Symbol of the asset: BTC, ETH, XAU, SOL, JITOSOL, SPY, NVDA, GOOGL, TSLA, AAPL",
  ).optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
  prompt_name: z.string().describe(
    "Forecast horizon: 1h for next-hour or 24h for next-day price intervals (default: 24h)",
  ).optional(),
});

export type GetInsightsLpProbabilitiesResponse =
  | TypesLPProbabilitiesResponse
  | string
  | string;

export const GetInsightsLpProbabilitiesResponse$zodSchema: z.ZodType<
  GetInsightsLpProbabilitiesResponse
> = z.union([
  TypesLPProbabilitiesResponse$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
