/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f10f599e30d8
 */

import * as z from "zod";
import {
  TypesPolymarketUpDownResponse,
  TypesPolymarketUpDownResponse$zodSchema,
} from "./typespolymarketupdownresponse.js";

export type GetInsightsPolymarketUpDown5minRequest = {
  asset?: string | undefined;
  horizon?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsPolymarketUpDown5minRequest$zodSchema: z.ZodType<
  GetInsightsPolymarketUpDown5minRequest
> = z.object({
  asset: z.string().describe("Symbol of the asset: BTC, ETH, SOL").optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  horizon: z.string().describe(
    "Forecast horizon: 1h for next-hour or 24h for next-day price intervals (default: 1h)",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
});

export type GetInsightsPolymarketUpDown5minResponse =
  | TypesPolymarketUpDownResponse
  | string
  | string;

export const GetInsightsPolymarketUpDown5minResponse$zodSchema: z.ZodType<
  GetInsightsPolymarketUpDown5minResponse
> = z.union([
  TypesPolymarketUpDownResponse$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
