/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesLiquidationProbabilityResponse,
  TypesLiquidationProbabilityResponse$zodSchema,
} from "./typesliquidationprobabilityresponse.js";

export type GetInsightsLiquidationRequest = {
  asset?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsLiquidationRequest$zodSchema: z.ZodType<
  GetInsightsLiquidationRequest
> = z.object({
  asset: z.string().describe(
    "the symbol of the asset: BTC, ETH, XAU, SOL, SPYX, NVDAX, TSLAX, AAPLX, GOOGLX",
  ).optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
});

export type GetInsightsLiquidationResponse =
  | TypesLiquidationProbabilityResponse
  | string
  | string;

export const GetInsightsLiquidationResponse$zodSchema: z.ZodType<
  GetInsightsLiquidationResponse
> = z.union([
  TypesLiquidationProbabilityResponse$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
