/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f0d137fb07d6
 */

import * as z from "zod";
import {
  TypesVolatilityResponse,
  TypesVolatilityResponse$zodSchema,
} from "./typesvolatilityresponse.js";

export type GetInsightsVolatilityRequest = {
  asset?: string | undefined;
  horizon?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetInsightsVolatilityRequest$zodSchema: z.ZodType<
  GetInsightsVolatilityRequest
> = z.object({
  asset: z.string().describe(
    "Symbol of the asset: BTC, ETH, XAU, SOL, JITOSOL, SPY, NVDA, GOOGL, TSLA, AAPL",
  ).optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  horizon: z.string().describe(
    "Forecast horizon: 1h for next-hour or 24h for next-day price intervals (default: 24h)",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
});

export type GetInsightsVolatilityResponse =
  | TypesVolatilityResponse
  | string
  | string;

export const GetInsightsVolatilityResponse$zodSchema: z.ZodType<
  GetInsightsVolatilityResponse
> = z.union([
  TypesVolatilityResponse$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
