/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cd221da1e939
 */

import * as z from "zod";
import {
  TypesPredictionPercentiles,
  TypesPredictionPercentiles$zodSchema,
} from "./typespredictionpercentiles.js";

export type GetPredictionPercentilesRequest = {
  asset?: string | undefined;
  days?: number | undefined;
  limit?: number | undefined;
};

export const GetPredictionPercentilesRequest$zodSchema: z.ZodType<
  GetPredictionPercentilesRequest
> = z.object({
  asset: z.string().describe(
    "the symbol of the asset: BTC, ETH, XAU, SOL, SPYX, NVDAX, TSLAX, AAPLX, GOOGLX",
  ).optional(),
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14). See 'Leaderboard - Latest Meta-Leaderboard'.",
  ).optional(),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
});

export type GetPredictionPercentilesResponse =
  | TypesPredictionPercentiles
  | string
  | string;

export const GetPredictionPercentilesResponse$zodSchema: z.ZodType<
  GetPredictionPercentilesResponse
> = z.union([
  TypesPredictionPercentiles$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
