/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesValidationScore,
  TypesValidationScore$zodSchema,
} from "./typesvalidationscore.js";

export type GetValidationScoresHistoricalRequest = {
  from: string;
  to: string;
  miner_uid?: number | undefined;
  asset?: string | undefined;
  time_increment?: number | undefined;
  time_length?: number | undefined;
};

export const GetValidationScoresHistoricalRequest$zodSchema: z.ZodType<
  GetValidationScoresHistoricalRequest
> = z.object({
  asset: z.string().describe(
    "The symbol of the asset: BTC, ETH, XAU, SOL, SPYX, NVDAX, TSLAX, AAPLX, GOOGLX (default BTC)",
  ).optional(),
  from: z.string().describe(
    "Start date (2025-02-03T10:19:04Z or 2025-02-03T17:19:04+07:00 or 2025-02-03)",
  ),
  miner_uid: z.int().describe("Optional miner ID to filter by").optional(),
  time_increment: z.int().describe(
    "the time interval (in seconds) of the validator prompt between each rate: 300 or 60 (default 300).",
  ).optional(),
  time_length: z.int().describe(
    "the length of time (in seconds) of the validator prompt from the start time: 86400 or 3600 (default 86400)",
  ).optional(),
  to: z.string().describe(
    "End date (2025-02-03T10:19:04Z or 2025-02-03T17:19:04+07:00 or 2025-02-03)",
  ),
});

export type GetValidationScoresHistoricalResponse =
  | Array<TypesValidationScore>
  | string
  | string;

export const GetValidationScoresHistoricalResponse$zodSchema: z.ZodType<
  GetValidationScoresHistoricalResponse
> = z.union([
  z.array(TypesValidationScore$zodSchema).describe("OK"),
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
