/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesPredictionResponse,
  TypesPredictionResponse$zodSchema,
} from "./typespredictionresponse.js";

export type GetV2PredictionLatestRequest = {
  miner: Array<number>;
  asset: string;
  time_increment: number;
  time_length: number;
  limit?: number | undefined;
};

export const GetV2PredictionLatestRequest$zodSchema: z.ZodType<
  GetV2PredictionLatestRequest
> = z.object({
  asset: z.string().describe(
    "the symbol of the asset: BTC, ETH, XAU, SOL, SPYX, NVDAX, TSLAX, AAPLX, GOOGLX",
  ),
  limit: z.int().describe(
    "Number of miners from the meta-leaderboard to use for the analysis (default is 10)",
  ).optional(),
  miner: z.array(z.int()).describe("a list of specific miners by their ID"),
  time_increment: z.int().describe(
    "the time interval (in seconds) of the validator prompt between each rate. 300 or 60.",
  ),
  time_length: z.int().describe(
    "the length of time (in seconds) of the validator prompt from the start time. 86400 or 3600.",
  ),
});

export type GetV2PredictionLatestResponse =
  | Array<TypesPredictionResponse>
  | string
  | string
  | string;

export const GetV2PredictionLatestResponse$zodSchema: z.ZodType<
  GetV2PredictionLatestResponse
> = z.union([
  z.array(TypesPredictionResponse$zodSchema).describe("OK"),
  z.string().describe("Bad Request"),
  z.string().describe("No prediction available"),
  z.string().describe("Internal Server Error"),
]);
