/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesLeaderboardItemV2,
  TypesLeaderboardItemV2$zodSchema,
} from "./typesleaderboarditemv2.js";

export type GetV2LeaderboardHistoricalRequest = {
  start_time: string;
  end_time: string;
  prompt_name?: string | undefined;
};

export const GetV2LeaderboardHistoricalRequest$zodSchema: z.ZodType<
  GetV2LeaderboardHistoricalRequest
> = z.object({
  end_time: z.string().describe(
    "an URL encoded ISO 8601 date/time to end at (2025-02-03T10:19:04Z or 2025-02-03T17:19:04+07:00 or 2025-02-03)",
  ),
  prompt_name: z.string().describe(
    "Prompt name, high for 1h prompt or low for 24h prompt",
  ).optional(),
  start_time: z.string().describe(
    "an URL encoded ISO 8601 date/time to start from (2025-02-03T10:19:04Z or 2025-02-03T17:19:04+07:00 or 2025-02-03)",
  ),
});

export type GetV2LeaderboardHistoricalResponse =
  | Array<TypesLeaderboardItemV2>
  | string;

export const GetV2LeaderboardHistoricalResponse$zodSchema: z.ZodType<
  GetV2LeaderboardHistoricalResponse
> = z.union([
  z.array(TypesLeaderboardItemV2$zodSchema).describe("OK"),
  z.string().describe("Internal Server Error"),
]);
