/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d29b09f4f5f7
 */

import * as z from "zod";
import {
  TypesPredictionResponse,
  TypesPredictionResponse$zodSchema,
} from "./typespredictionresponse.js";

export type GetV2PredictionBestRequest = {
  asset: string;
  time_increment: number;
  time_length: number;
};

export const GetV2PredictionBestRequest$zodSchema: z.ZodType<
  GetV2PredictionBestRequest
> = z.object({
  asset: z.string().describe(
    "the symbol of the asset: BTC, ETH, XAU, SOL, SPYX, NVDAX, TSLAX, AAPLX, GOOGLX",
  ),
  time_increment: z.int().describe(
    "the time interval (in seconds) of the validator prompt between each rate. 300 or 60.",
  ),
  time_length: z.int().describe(
    "the length of time (in seconds) of the validator prompt from the start time. 86400 or 3600.",
  ),
});

export type GetV2PredictionBestResponse =
  | Array<TypesPredictionResponse>
  | string
  | string
  | string;

export const GetV2PredictionBestResponse$zodSchema: z.ZodType<
  GetV2PredictionBestResponse
> = z.union([
  z.array(TypesPredictionResponse$zodSchema).describe("OK"),
  z.string().describe("Bad Request"),
  z.string().describe("No prediction available"),
  z.string().describe("Internal Server Error"),
]);
