/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesLeaderboardItemV2,
  TypesLeaderboardItemV2$zodSchema,
} from "./typesleaderboarditemv2.js";

export type GetV2LeaderboardLatestRequest = {
  prompt_name?: string | undefined;
};

export const GetV2LeaderboardLatestRequest$zodSchema: z.ZodType<
  GetV2LeaderboardLatestRequest
> = z.object({
  prompt_name: z.string().describe(
    "Prompt name, high for 1h prompt or low for 24h prompt",
  ).optional(),
});

export type GetV2LeaderboardLatestResponse =
  | Array<TypesLeaderboardItemV2>
  | string;

export const GetV2LeaderboardLatestResponse$zodSchema: z.ZodType<
  GetV2LeaderboardLatestResponse
> = z.union([
  z.array(TypesLeaderboardItemV2$zodSchema).describe("OK"),
  z.string().describe("Internal Server Error"),
]);
