/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3dd0a5b03724
 */

import * as z from "zod";
import {
  TypesLeaderboardItemV2,
  TypesLeaderboardItemV2$zodSchema,
} from "./typesleaderboarditemv2.js";

export type GetV2MetaLeaderboardHistoricalRequest = {
  start_time: string;
  prompt_name?: string | undefined;
  days?: number | undefined;
};

export const GetV2MetaLeaderboardHistoricalRequest$zodSchema: z.ZodType<
  GetV2MetaLeaderboardHistoricalRequest
> = z.object({
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14)",
  ).optional(),
  prompt_name: z.string().describe(
    "Prompt name, high for 1h prompt or low for 24h prompt",
  ).optional(),
  start_time: z.string().describe(
    "an URL encoded ISO 8601 date/time to start from (2025-02-03T10:19:04Z or 2025-02-03T17:19:04+07:00 or 2025-02-03)",
  ),
});

export type GetV2MetaLeaderboardHistoricalResponse =
  | Array<TypesLeaderboardItemV2>
  | string;

export const GetV2MetaLeaderboardHistoricalResponse$zodSchema: z.ZodType<
  GetV2MetaLeaderboardHistoricalResponse
> = z.union([
  z.array(TypesLeaderboardItemV2$zodSchema).describe("OK"),
  z.string().describe("Internal Server Error"),
]);
