/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 368b3cff71b3
 */

import * as z from "zod";
import {
  TypesValidationScore,
  TypesValidationScore$zodSchema,
} from "./typesvalidationscore.js";

export type GetValidationScoresLatestRequest = {
  asset?: string | undefined;
  time_increment?: number | undefined;
  time_length?: number | undefined;
};

export const GetValidationScoresLatestRequest$zodSchema: z.ZodType<
  GetValidationScoresLatestRequest
> = z.object({
  asset: z.string().describe(
    "The symbol of the asset: BTC, ETH, XAU, SOL, SPYX, NVDAX, TSLAX, AAPLX, GOOGLX (default BTC)",
  ).optional(),
  time_increment: z.int().describe(
    "the time interval (in seconds) of the validator prompt between each rate: 300 or 60 (default 300).",
  ).optional(),
  time_length: z.int().describe(
    "the length of time (in seconds) of the validator prompt from the start time: 86400 or 3600 (default 86400)",
  ).optional(),
});

export type GetValidationScoresLatestResponse =
  | Array<TypesValidationScore>
  | string;

export const GetValidationScoresLatestResponse$zodSchema: z.ZodType<
  GetValidationScoresLatestResponse
> = z.union([
  z.array(TypesValidationScore$zodSchema).describe("OK"),
  z.string().describe("Internal Server Error"),
]);
