/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eb2c81b26ab7
 */

import * as z from "zod";
import {
  TypesLeaderboardItemV2,
  TypesLeaderboardItemV2$zodSchema,
} from "./typesleaderboarditemv2.js";

export type GetV2MetaLeaderboardLatestRequest = {
  days?: number | undefined;
  prompt_name?: string | undefined;
};

export const GetV2MetaLeaderboardLatestRequest$zodSchema: z.ZodType<
  GetV2MetaLeaderboardLatestRequest
> = z.object({
  days: z.int().describe(
    "Number of days to aggregate for the meta-leaderboard (default is 14)",
  ).optional(),
  prompt_name: z.string().describe(
    "Prompt name, high for 1h prompt or low for 24h prompt",
  ).optional(),
});

export type GetV2MetaLeaderboardLatestResponse =
  | Array<TypesLeaderboardItemV2>
  | string;

export const GetV2MetaLeaderboardLatestResponse$zodSchema: z.ZodType<
  GetV2MetaLeaderboardLatestResponse
> = z.union([
  z.array(TypesLeaderboardItemV2$zodSchema).describe("OK"),
  z.string().describe("Internal Server Error"),
]);
