/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesMinerValidationResponse,
  TypesMinerValidationResponse$zodSchema,
} from "./typesminervalidationresponse.js";

export type GetValidationMinerRequest = { uid: number };

export const GetValidationMinerRequest$zodSchema: z.ZodType<
  GetValidationMinerRequest
> = z.object({
  uid: z.int().describe("ID of the miner to get validation for"),
});

export type GetValidationMinerResponse =
  | TypesMinerValidationResponse
  | string
  | string;

export const GetValidationMinerResponse$zodSchema: z.ZodType<
  GetValidationMinerResponse
> = z.union([
  TypesMinerValidationResponse$zodSchema,
  z.string().describe("Bad Request"),
  z.string().describe("Internal Server Error"),
]);
