/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesPredictionResponse,
  TypesPredictionResponse$zodSchema,
} from "./typespredictionresponse.js";

export type GetV2PredictionHistoricalRequest = {
  miner: Array<number>;
  asset: string;
  start_time: string;
  time_increment: number;
  time_length: number;
};

export const GetV2PredictionHistoricalRequest$zodSchema: z.ZodType<
  GetV2PredictionHistoricalRequest
> = z.object({
  asset: z.string().describe(
    "the symbol of the asset: BTC, ETH, XAU, SOL, SPYX, NVDAX, TSLAX, AAPLX, GOOGLX",
  ),
  miner: z.array(z.int()).describe("a list of specific miners by their ID"),
  start_time: z.string().describe(
    "an ISO 8601 date/time to start the historical rates from (2025-02-03T10:19:04Z or 2025-02-03T17:19:04+07:00 or 2025-02-03)",
  ),
  time_increment: z.int().describe(
    "the time interval (in seconds) of the validator prompt between each rate. 300 or 60.",
  ),
  time_length: z.int().describe(
    "the length of time (in seconds) of the validator prompt from the start time. 86400 or 3600.",
  ),
});

export type GetV2PredictionHistoricalResponse =
  | Array<TypesPredictionResponse>
  | string
  | string
  | string;

export const GetV2PredictionHistoricalResponse$zodSchema: z.ZodType<
  GetV2PredictionHistoricalResponse
> = z.union([
  z.array(TypesPredictionResponse$zodSchema).describe("OK"),
  z.string().describe("Bad Request"),
  z.string().describe("No prediction available"),
  z.string().describe("Internal Server Error"),
]);
