/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d90c6c784ca5
 */

import * as z from "zod";

export type Security = { bearerAuth: string };

export const Security$zodSchema: z.ZodType<Security> = z.object({
  bearerAuth: z.string().describe("HTTP Bearer"),
});
