/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 30309d983d43
 */

import * as z from "zod";
import {
  TypesPriceProbabilityData,
  TypesPriceProbabilityData$zodSchema,
} from "./typespriceprobabilitydata.js";

export type TypesLPProbabilitiesResponse = {
  current_price?: number | undefined;
  data?: TypesPriceProbabilityData | undefined;
};

export const TypesLPProbabilitiesResponse$zodSchema: z.ZodType<
  TypesLPProbabilitiesResponse
> = z.object({
  current_price: z.number().optional(),
  data: TypesPriceProbabilityData$zodSchema.optional(),
});
