/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesStayInIntervalProbability = {
  twentyFour?: number | undefined;
};

export const TypesStayInIntervalProbability$zodSchema: z.ZodType<
  TypesStayInIntervalProbability
> = z.object({
  twentyFour: z.number().optional(),
});
