/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c749758c8737
 */

import * as z from "zod";

export type TypesPercentileTyped = {
  zeroDot2?: number | undefined;
  zeroDot5?: number | undefined;
  zeroDot05?: number | undefined;
  zeroDot005?: number | undefined;
  zeroDot8?: number | undefined;
  zeroDot35?: number | undefined;
  zeroDot65?: number | undefined;
  zeroDot95?: number | undefined;
  zeroDot995?: number | undefined;
};

export const TypesPercentileTyped$zodSchema: z.ZodType<TypesPercentileTyped> = z
  .object({
    zeroDot005: z.number().optional(),
    zeroDot05: z.number().optional(),
    zeroDot2: z.number().optional(),
    zeroDot35: z.number().optional(),
    zeroDot5: z.number().optional(),
    zeroDot65: z.number().optional(),
    zeroDot8: z.number().optional(),
    zeroDot95: z.number().optional(),
    zeroDot995: z.number().optional(),
  });
