/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 92f8183f93af
 */

import * as z from "zod";
import { TypesForecast, TypesForecast$zodSchema } from "./typesforecast.js";
import { TypesRealized, TypesRealized$zodSchema } from "./typesrealized.js";

export type TypesVolatilityResponse = {
  current_price?: number | undefined;
  forecast_future?: TypesForecast | undefined;
  forecast_past?: TypesForecast | undefined;
  realized?: TypesRealized | undefined;
};

export const TypesVolatilityResponse$zodSchema: z.ZodType<
  TypesVolatilityResponse
> = z.object({
  current_price: z.number().optional(),
  forecast_future: TypesForecast$zodSchema.optional(),
  forecast_past: TypesForecast$zodSchema.optional(),
  realized: TypesRealized$zodSchema.optional(),
});
