/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesForecastDataTyped,
  TypesForecastDataTyped$zodSchema,
} from "./typesforecastdatatyped.js";

export type TypesPredictionPercentiles = {
  current_price?: number | undefined;
  forecast_future?: TypesForecastDataTyped | undefined;
};

export const TypesPredictionPercentiles$zodSchema: z.ZodType<
  TypesPredictionPercentiles
> = z.object({
  current_price: z.number().optional(),
  forecast_future: TypesForecastDataTyped$zodSchema.optional(),
});
