/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d9cbef81ef01
 */

import * as z from "zod";
import {
  TypesPriceReturn,
  TypesPriceReturn$zodSchema,
} from "./typespricereturn.js";

export type TypesRealized = {
  average_volatility?: number | undefined;
  prices?: Array<TypesPriceReturn> | undefined;
  volatility?: Array<number> | undefined;
};

export const TypesRealized$zodSchema: z.ZodType<TypesRealized> = z.object({
  average_volatility: z.number().optional(),
  prices: z.array(TypesPriceReturn$zodSchema).optional(),
  volatility: z.array(z.number()).optional(),
});
