/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5200cc42f571
 */

import * as z from "zod";
import { TypesInterval, TypesInterval$zodSchema } from "./typesinterval.js";
import {
  TypesStayInIntervalProbability,
  TypesStayInIntervalProbability$zodSchema,
} from "./typesstayinintervalprobability.js";

export type TypesIntervalData = {
  expected_impermanent_loss?: number | undefined;
  expected_time_in_interval?: number | undefined;
  interval?: TypesInterval | undefined;
  probability_to_stay_in_interval?: TypesStayInIntervalProbability | undefined;
};

export const TypesIntervalData$zodSchema: z.ZodType<TypesIntervalData> = z
  .object({
    expected_impermanent_loss: z.number().optional(),
    expected_time_in_interval: z.number().optional(),
    interval: TypesInterval$zodSchema.optional(),
    probability_to_stay_in_interval: TypesStayInIntervalProbability$zodSchema
      .optional(),
  });
