/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesMinerValidationResponse = {
  reason?: string | undefined;
  response_time?: string | undefined;
  validated?: boolean | undefined;
};

export const TypesMinerValidationResponse$zodSchema: z.ZodType<
  TypesMinerValidationResponse
> = z.object({
  reason: z.string().optional(),
  response_time: z.string().optional(),
  validated: z.boolean().optional(),
});
