/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesLeaderboardItemV2 = {
  coldkey?: string | undefined;
  ip_address?: string | undefined;
  neuron_uid?: number | undefined;
  rewards?: number | undefined;
  updated_at?: string | undefined;
};

export const TypesLeaderboardItemV2$zodSchema: z.ZodType<
  TypesLeaderboardItemV2
> = z.object({
  coldkey: z.string().optional(),
  ip_address: z.string().optional(),
  neuron_uid: z.int().optional(),
  rewards: z.number().optional(),
  updated_at: z.string().optional(),
});
