/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesForecast = {
  average_volatility?: number | undefined;
  volatility?: Array<number> | undefined;
};

export const TypesForecast$zodSchema: z.ZodType<TypesForecast> = z.object({
  average_volatility: z.number().optional(),
  volatility: z.array(z.number()).optional(),
});
