/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5974c841306c
 */

import * as z from "zod";
import {
  TypesHourlyProbability,
  TypesHourlyProbability$zodSchema,
} from "./typeshourlyprobability.js";

export type TypesLiquidationProbability = {
  long_liquidation_probability?: TypesHourlyProbability | undefined;
  price_change?: string | undefined;
  short_liquidation_probability?: TypesHourlyProbability | undefined;
};

export const TypesLiquidationProbability$zodSchema: z.ZodType<
  TypesLiquidationProbability
> = z.object({
  long_liquidation_probability: TypesHourlyProbability$zodSchema.optional(),
  price_change: z.string().optional(),
  short_liquidation_probability: TypesHourlyProbability$zodSchema.optional(),
});
