/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d5cb59b03112
 */

import * as z from "zod";

export type TypesOptionPricingResponse = {
  call_options?: { [k: string]: number } | undefined;
  current_price?: number | undefined;
  expiry_time?: string | undefined;
  put_options?: { [k: string]: number } | undefined;
};

export const TypesOptionPricingResponse$zodSchema: z.ZodType<
  TypesOptionPricingResponse
> = z.object({
  call_options: z.record(z.string(), z.number()).optional(),
  current_price: z.number().optional(),
  expiry_time: z.string().optional(),
  put_options: z.record(z.string(), z.number()).optional(),
});
