/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 18c02bf6f06b
 */

import * as z from "zod";

export type TypesForecast = {
  average_volatility?: number | undefined;
  volatility?: Array<number> | undefined;
};

export const TypesForecast$zodSchema: z.ZodType<TypesForecast> = z.object({
  average_volatility: z.number().optional(),
  volatility: z.array(z.number()).optional(),
});
