/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1e8d61a60be7
 */

import * as z from "zod";

export type TypesPriceReturn = {
  price?: number | undefined;
  returns?: number | undefined;
};

export const TypesPriceReturn$zodSchema: z.ZodType<TypesPriceReturn> = z.object(
  {
    price: z.number().optional(),
    returns: z.number().optional(),
  },
);
