/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a2aa70254416
 */

import * as z from "zod";

export type TypesHourlyProbability = {
  twelve?: number | undefined;
  eighteen?: number | undefined;
  twentyFour?: number | undefined;
  six?: number | undefined;
};

export const TypesHourlyProbability$zodSchema: z.ZodType<
  TypesHourlyProbability
> = z.object({
  eighteen: z.number().optional(),
  six: z.number().optional(),
  twelve: z.number().optional(),
  twentyFour: z.number().optional(),
});
