/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0771be3e97bb
 */

import * as z from "zod";
import {
  TypesPercentileTyped,
  TypesPercentileTyped$zodSchema,
} from "./typespercentiletyped.js";

export type TypesForecastDataTyped = {
  percentiles?: Array<TypesPercentileTyped> | undefined;
};

export const TypesForecastDataTyped$zodSchema: z.ZodType<
  TypesForecastDataTyped
> = z.object({
  percentiles: z.array(TypesPercentileTyped$zodSchema).optional(),
});
