/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 059d78bddc06
 */

import * as z from "zod";

export type TypesPolymarketUpDownResponse = {
  best_ask_price?: number | undefined;
  best_ask_size?: number | undefined;
  best_bid_price?: number | undefined;
  best_bid_size?: number | undefined;
  current_outcome?: string | undefined;
  current_price?: number | undefined;
  current_time?: string | undefined;
  event_creation_time?: string | undefined;
  event_end_time?: string | undefined;
  event_start_time?: string | undefined;
  polymarket_last_trade_outcome?: string | undefined;
  polymarket_last_trade_price?: number | undefined;
  polymarket_last_trade_time?: string | undefined;
  polymarket_outcome?: string | undefined;
  polymarket_probability_up?: number | undefined;
  slug?: string | undefined;
  start_price?: number | undefined;
  synth_outcome?: string | undefined;
  synth_probability_up?: number | undefined;
};

export const TypesPolymarketUpDownResponse$zodSchema: z.ZodType<
  TypesPolymarketUpDownResponse
> = z.object({
  best_ask_price: z.number().optional(),
  best_ask_size: z.number().optional(),
  best_bid_price: z.number().optional(),
  best_bid_size: z.number().optional(),
  current_outcome: z.string().optional(),
  current_price: z.number().optional(),
  current_time: z.string().optional(),
  event_creation_time: z.string().optional(),
  event_end_time: z.string().optional(),
  event_start_time: z.string().optional(),
  polymarket_last_trade_outcome: z.string().optional(),
  polymarket_last_trade_price: z.number().optional(),
  polymarket_last_trade_time: z.string().optional(),
  polymarket_outcome: z.string().optional(),
  polymarket_probability_up: z.number().optional(),
  slug: z.string().optional(),
  start_price: z.number().optional(),
  synth_outcome: z.string().optional(),
  synth_probability_up: z.number().optional(),
});
