/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dc2a3cbff715
 */

import * as z from "zod";

export type TypesPredictionResponse = {
  miner_uid?: number | undefined;
  predictions?: Array<Array<number>> | undefined;
  start_time?: number | undefined;
};

export const TypesPredictionResponse$zodSchema: z.ZodType<
  TypesPredictionResponse
> = z.object({
  miner_uid: z.int().optional(),
  predictions: z.array(z.array(z.number())).optional(),
  start_time: z.int().optional(),
});
