/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesProbabilityDirection = {
  probability_above?: { [k: string]: number } | undefined;
  probability_below?: { [k: string]: number } | undefined;
};

export const TypesProbabilityDirection$zodSchema: z.ZodType<
  TypesProbabilityDirection
> = z.object({
  probability_above: z.record(z.string(), z.number()).optional(),
  probability_below: z.record(z.string(), z.number()).optional(),
});
