/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 013ffc72af87
 */

import * as z from "zod";

export type TypesInterval = {
  full_width?: string | undefined;
  lower_bound?: number | undefined;
  upper_bound?: number | undefined;
};

export const TypesInterval$zodSchema: z.ZodType<TypesInterval> = z.object({
  full_width: z.string().optional(),
  lower_bound: z.number().optional(),
  upper_bound: z.number().optional(),
});
