/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 07372bb92421
 */

import * as z from "zod";

export type TypesLimitlessMarket = {
  best_ask_price?: number | undefined;
  best_bid_price?: number | undefined;
  current_price?: number | undefined;
  current_time?: string | undefined;
  event_creation_time?: string | undefined;
  event_end_time?: string | undefined;
  event_outcome_prices?: Array<number> | undefined;
  forecast_start_time?: string | undefined;
  market_outcome?: string | undefined;
  market_probability_up?: number | undefined;
  slug?: string | undefined;
  start_price?: number | undefined;
  synth_outcome?: string | undefined;
  synth_probability_up?: number | undefined;
};

export const TypesLimitlessMarket$zodSchema: z.ZodType<TypesLimitlessMarket> = z
  .object({
    best_ask_price: z.number().optional(),
    best_bid_price: z.number().optional(),
    current_price: z.number().optional(),
    current_time: z.string().optional(),
    event_creation_time: z.string().optional(),
    event_end_time: z.string().optional(),
    event_outcome_prices: z.array(z.number()).optional(),
    forecast_start_time: z.string().optional(),
    market_outcome: z.string().optional(),
    market_probability_up: z.number().optional(),
    slug: z.string().optional(),
    start_price: z.number().optional(),
    synth_outcome: z.string().optional(),
    synth_probability_up: z.number().optional(),
  });
