/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesIntervalData,
  TypesIntervalData$zodSchema,
} from "./typesintervaldata.js";

export type TypesLPBoundsResponse = {
  current_price?: number | undefined;
  data?: Array<TypesIntervalData> | undefined;
};

export const TypesLPBoundsResponse$zodSchema: z.ZodType<TypesLPBoundsResponse> =
  z.object({
    current_price: z.number().optional(),
    data: z.array(TypesIntervalData$zodSchema).optional(),
  });
