/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1675acae7bbf
 */

import * as z from "zod";

export type TypesValidationScore = {
  asset?: string | undefined;
  crps?: number | undefined;
  miner_uid?: number | undefined;
  prompt_score?: number | undefined;
  scored_time?: string | undefined;
  time_length?: number | undefined;
};

export const TypesValidationScore$zodSchema: z.ZodType<TypesValidationScore> = z
  .object({
    asset: z.string().optional(),
    crps: z.number().optional(),
    miner_uid: z.int().optional(),
    prompt_score: z.number().optional(),
    scored_time: z.string().optional(),
    time_length: z.int().optional(),
  });
