/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesLiquidationProbability,
  TypesLiquidationProbability$zodSchema,
} from "./typesliquidationprobability.js";

export type TypesLiquidationProbabilityResponse = {
  current_price?: number | undefined;
  data?: Array<TypesLiquidationProbability> | undefined;
};

export const TypesLiquidationProbabilityResponse$zodSchema: z.ZodType<
  TypesLiquidationProbabilityResponse
> = z.object({
  current_price: z.number().optional(),
  data: z.array(TypesLiquidationProbability$zodSchema).optional(),
});
