/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ec83cb19212a
 */

import * as z from "zod";

export type TypesPriceRangeMarket = {
  best_ask_price?: number | undefined;
  best_ask_size?: number | undefined;
  best_bid_price?: number | undefined;
  best_bid_size?: number | undefined;
  cmp_type?: string | undefined;
  current_outcome?: number | undefined;
  current_price?: number | undefined;
  current_time?: string | undefined;
  event_creation_time?: string | undefined;
  event_end_time?: string | undefined;
  event_start_time?: string | undefined;
  polymarket_last_trade_outcome?: number | undefined;
  polymarket_last_trade_price?: number | undefined;
  polymarket_last_trade_time?: string | undefined;
  polymarket_outcome?: number | undefined;
  polymarket_probability?: number | undefined;
  ref_prices?: Array<number> | undefined;
  slug?: string | undefined;
  synth_outcome?: number | undefined;
  synth_probability?: number | undefined;
  title?: string | undefined;
};

export const TypesPriceRangeMarket$zodSchema: z.ZodType<TypesPriceRangeMarket> =
  z.object({
    best_ask_price: z.number().optional(),
    best_ask_size: z.number().optional(),
    best_bid_price: z.number().optional(),
    best_bid_size: z.number().optional(),
    cmp_type: z.string().optional(),
    current_outcome: z.int().optional(),
    current_price: z.number().optional(),
    current_time: z.string().optional(),
    event_creation_time: z.string().optional(),
    event_end_time: z.string().optional(),
    event_start_time: z.string().optional(),
    polymarket_last_trade_outcome: z.int().optional(),
    polymarket_last_trade_price: z.number().optional(),
    polymarket_last_trade_time: z.string().optional(),
    polymarket_outcome: z.int().optional(),
    polymarket_probability: z.number().optional(),
    ref_prices: z.array(z.number()).optional(),
    slug: z.string().optional(),
    synth_outcome: z.int().optional(),
    synth_probability: z.number().optional(),
    title: z.string().optional(),
  });
