/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2b4ccec58e5d
 */

import * as z from "zod";
import {
  TypesProbabilityDirection,
  TypesProbabilityDirection$zodSchema,
} from "./typesprobabilitydirection.js";

export type TypesPriceProbabilityData = {
  twentyFourh?: TypesProbabilityDirection | undefined;
};

export const TypesPriceProbabilityData$zodSchema: z.ZodType<
  TypesPriceProbabilityData
> = z.object({
  twentyFourh: TypesProbabilityDirection$zodSchema.optional(),
});
